server:
  port: 9099
  max-http-header-size: 40KB

spring:
  datasource:
    url: jdbc:mysql://${DATASOURCE_URL}:3306/accesscontrol?createDatabaseIfNotExist=true
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 600000
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        dialect: org.hibernate.dialect.MySQL5Dialect
        use_sql_comments: false
        format_sql: false
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
      # Naming strategy
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
  jackson:
    default-property-inclusion: NON_NULL
